name: Deploy on Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /home/timer/HammerTime
          git reset --hard
          git pull origin main

      - name: Install dependencies
        run: |
          cd /home/timer/HammerTime
          npm install

      - name: Restart service
        run: sudo /bin/systemctl restart curling-timer.service

      - name: Refresh Running Brower
        run: /home/timer/Desktop/start-kiosk.sh
