name: Deploy on Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux, pi] # Make sure these match your runner's labels

    steps:
      - name: Pull latest code
        run: |
          cd /home/timer/HammerTime
          git reset --hard
          git pull origin main

      - name: Install dependencies
        run: |
          cd /home/timer/HammerTime
          npm install

      - name: Restart service
        run: sudo systemctl restart curling-timer.service
